### ISSUE TITLE
Example Chat App not working

### ISSUE THREAD

**Issue by BerndWessels** [davidmarne/flutter_built_redux#6]
Hi

Thanks for updating the dependencies.

I just cloned the repo and build the example chat app, but it has some problems now.

Can you please look into this, thank you.

`main.dart`

![dart2](https://user-images.githubusercontent.com/1776695/30984943-550c1c86-a4eb-11e7-829a-4f6eafba1423.png)

**Comment by davidmarne** [comment]
This is bizarre. At first I could not reproduce locally, but I did a flutter upgrade and started seeing the analysis issues. It looks like anything >= 0.0.8 yields the analysis errors.

ChatScreenState does not inherit from _BottomNavigationBarState at all, so I'm pretty confused why the analyzer thinks that is the state variable is inherited from that object. It also thinks actions is inherited from PaginatedDataTable, which ChatScreenState does not extend. 

Even weirder, the app still builds and runs just fine on my android phone. Gonna have to noodle on this, because I've got no solution right now.

Do you have any guesses?

**Comment by BerndWessels** [comment]
Indeed, I am trying to figure it out, but there is no clue why the analyzer gets so confused.

**Comment by scheglov** [comment]
I was not able to reproduce the problem. Cloned, ran `dart tool/build.dart`, opened the project in IDEA - no errors.

**Comment by davidmarne** [comment]
Changes made in https://github.com/davidmarne/flutter_built_redux/releases/tag/0.2.0 have made this issue obsolete. State and actions are no longer public class variables, they are passed your build function. This seemed to fix whatever analysis issues we were seeing.
